[build]
  command = ""
  
[build.environment]
  FRONTEND_ORIGIN = "https://chowacopdf.netlify.app"
  
[functions]
  directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/api/:splat"
status = 200