[build]
  command = ""               # No build step required
  publish = ""               # No publish directory needed
  functions = "netlify/functions"  # Location of your serverless functions
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


[functions]
  external_node_modules = ["express", "@supabase/supabase-js", "multer", "pdf-parse", "openai", "cors", "dotenv"]
  node_bundler = "esbuild"