[build]
  command = ""               # No build step required
  publish = ""               # No publish directory needed
  functions = "netlify/functions"  # Location of your serverless functions
  node_bundler = "esbuild"

[build.environment]
  FRONTEND_ORIGIN = "https://chowacopdf.netlify.app"

[functions]
  external_node_modules = ["express", "@supabase/supabase-js", "multer", "pdf-parse", "openai", "cors", "dotenv"]
  node_bundler = "esbuild"