[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  FRONTEND_ORIGIN = "https://chowacopdf.netlify.app"

[functions]
  external_node_modules = ["express", "serverless-http", "multer", "@supabase/supabase-js", "pdf-parse", "openai", "cors", "dotenv"]
  node_bundler = "esbuild"
